services:
  steps_bot:
    build: .
    container_name: steps_bot
    restart: always
    env_file:
      - .env
    command: python app/steps_bot/polling.py
    environment:
      - PYTHONPATH=/app
      - MEDIA_ROOT=/app/media
    ports:
      - "8080:8080"
    volumes:
      - .:/app
      - ./logs:/app/logs
      - media:/app/media
    depends_on:
      - postgres

  postgres:
    image: postgres:15
    container_name: pg_steps
    restart: always
    ports:
      - "5423:5432"
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data

  django_admin:
    build: .
    container_name: django_admin
    command: >
      python app/admin/manage.py runserver 0.0.0.0:8001
    ports:
      - "8001:8001"
    env_file:
      - .env
    environment:
      - PYTHONPATH=/app
      - MEDIA_ROOT=/app/media
    volumes:
      - .:/app
      - ./staticfiles:/app/staticfiles
      - media:/app/media
    depends_on:
      - postgres

  fastapi:
    build: .
    container_name: fastapi_admin
    command: >
      uvicorn app.steps_bot.api.admin:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - PYTHONPATH=/app
    volumes:
      - .:/app
    depends_on:
      - postgres

volumes:
  pgdata:
  media:
