# Generated by Django 5.2.3 on 2025-08-26 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotSetting',
            fields=[
                ('key', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='Ключ')),
                ('value', models.TextField(verbose_name='Значение')),
            ],
            options={
                'verbose_name': 'Ссылка на поддержку',
                'verbose_name_plural': 'Ссылка на поддержку',
                'db_table': 'bot_settings',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=64, unique=True, verbose_name='Код')),
                ('max_uses', models.IntegerField(default=1, verbose_name='Лимит использований')),
                ('used_count', models.IntegerField(default=0, verbose_name='Использовано')),
                ('valid_from', models.DateTimeField(blank=True, null=True, verbose_name='Действует с')),
                ('valid_to', models.DateTimeField(blank=True, null=True, verbose_name='Действует до')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(verbose_name='Создан')),
            ],
            options={
                'verbose_name': 'Промокод',
                'verbose_name_plural': 'Промокоды',
                'db_table': 'promo_codes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PromoGroup',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=60, unique=True, verbose_name='Название')),
                ('discount_percent', models.IntegerField(default=0, verbose_name='Скидка, %')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('created_at', models.DateTimeField(verbose_name='Создана')),
            ],
            options={
                'verbose_name': 'Группа промокодов',
                'verbose_name_plural': 'Группы промокодов',
                'db_table': 'promo_groups',
                'managed': False,
            },
        ),
    ]
