# Generated by Django 5.2.3 on 2025-10-19 14:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_botsetting_promocode_promogroup'),
    ]

    operations = [
        migrations.CreateModel(
            name='Broadcast',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.TextField(blank=True, null=True, verbose_name='Текст')),
                ('media_type', models.CharField(choices=[('none', 'Нет'), ('photo', 'Фото'), ('video', 'Видео')], default='none', max_length=10, verbose_name='Тип медиа')),
                ('telegram_file_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='Telegram file_id')),
                ('media_url', models.CharField(blank=True, max_length=1024, null=True, verbose_name='URL медиа')),
                ('media_file', models.FileField(blank=True, null=True, upload_to='uploads/broadcasts', verbose_name='Файл медиа')),
                ('scheduled_at', models.DateTimeField(blank=True, null=True, verbose_name='Отправить в')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Отправлено')),
                ('status', models.CharField(default='pending', max_length=10, verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Рассылка',
                'verbose_name_plural': 'Рассылки',
                'db_table': 'broadcasts',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PVZ',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_address', models.CharField(max_length=255, verbose_name='Полный адрес')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
            ],
            options={
                'verbose_name': 'Пункт выдачи',
                'verbose_name_plural': 'Пункты выдачи',
                'db_table': 'pvz',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('reward_points', models.IntegerField(default=0, verbose_name='Начислено баллов')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата регистрации')),
            ],
            options={
                'verbose_name': 'Реферал',
                'verbose_name_plural': 'Рефералы',
                'db_table': 'referrals',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='botsetting',
            options={'managed': False, 'verbose_name': 'Настройка бота', 'verbose_name_plural': 'Настройки бота'},
        ),
    ]
