"""initial schema

Revision ID: e303faa8a265
Revises: 
Create Date: 2025-06-26 02:05:42.363984

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e303faa8a265'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contents',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('media_type', sa.Enum('NONE', 'PHOTO', 'VIDEO', name='mediatype'), nullable=False),
    sa.Column('telegram_file_id', sa.String(length=255), nullable=True),
    sa.Column('media_url', sa.String(length=1024), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('families',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('balance', sa.Integer(), nullable=False),
    sa.Column('step_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('temperature_coefficients',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('walk_form', sa.Enum('STROLLER', 'DOG', 'STROLLER_DOG', name='walkform'), nullable=False),
    sa.Column('min_temp_c', sa.SmallInteger(), nullable=False),
    sa.Column('max_temp_c', sa.SmallInteger(), nullable=False),
    sa.Column('coefficient', sa.SmallInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('min_temp_c <= max_temp_c', name='ck_temp_range'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_tempcoeff', 'temperature_coefficients', ['walk_form', 'min_temp_c', 'max_temp_c'], unique=True)
    op.create_table('walk_form_coefficients',
    sa.Column('walk_form', sa.Enum('STROLLER', 'DOG', 'STROLLER_DOG', name='walkform'), nullable=False),
    sa.Column('coefficient', sa.SmallInteger(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('walk_form')
    )
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('first_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('father_name', sa.String(length=100), nullable=True),
    sa.Column('last_lat', sa.Float(), nullable=True),
    sa.Column('last_lon', sa.Float(), nullable=True),
    sa.Column('step_count', sa.Integer(), nullable=False),
    sa.Column('family_id', sa.Integer(), nullable=True),
    sa.Column('balance', sa.Integer(), nullable=False),
    sa.Column('role', sa.Enum('USER', 'ADMIN', name='userrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['family_id'], ['families.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_family_id'), 'users', ['family_id'], unique=False)
    op.create_index(op.f('ix_users_telegram_id'), 'users', ['telegram_id'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('family_invitations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('family_id', sa.Integer(), nullable=False),
    sa.Column('inviter_id', sa.BigInteger(), nullable=False),
    sa.Column('invitee_id', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ACCEPTED', 'DECLINED', 'CANCELED', name='familyinvitestatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('responded_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['family_id'], ['families.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['invitee_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['inviter_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('family_id', 'invitee_id', name='uq_invite_once')
    )
    op.create_index(op.f('ix_family_invitations_status'), 'family_invitations', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_family_invitations_status'), table_name='family_invitations')
    op.drop_table('family_invitations')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_telegram_id'), table_name='users')
    op.drop_index(op.f('ix_users_family_id'), table_name='users')
    op.drop_table('users')
    op.drop_table('walk_form_coefficients')
    op.drop_index('ix_tempcoeff', table_name='temperature_coefficients')
    op.drop_table('temperature_coefficients')
    op.drop_table('families')
    op.drop_table('contents')
    # ### end Alembic commands ###
